
stages:         
  - client_build_and_test
  - server_build_and_test

client-build-job: 
  image: node:latest
  stage: client_build_and_test
  script:
    - cd client
    - npm install
    - npm run build
    - npm test
  artifacts:
    paths:
      - client/node_modules

client-test-job:
  image: node:latest
  stage: client_build_and_test
  script:
    - cd server
    - npm install
    - npm run build
    - npm test
  artifacts:
    paths:
      - server/node_modules
  
