
stages:         
  - client_test
  - client_build
  - server_test
  - server_build

variables:
  CI: "false"

client-test: 
  image: node:latest
  stage: client_test
  script:
    - cd client
    - npm install
    - npm run test
  artifacts:
    paths:
      - node_modules

client-build:
  image: node:latest
  stage: client_build
  script:
    - cd client
    - npm run install
    - npm run build
  artifacts:
    paths:
      - node_modules
    
server-test: 
  image: node:latest
  stage: client_test
  script:
    - cd server
    - npm install
    - npm run test
  artifacts:
    paths:
      - node_modules

server-build:
  image: node:latest
  stage: client_build
  script:
    - cd server
    - npm run install
    - npm run build
  artifacts:
    paths:
      - node_modules
  
