
stages:         
  - client_test
  - client_build

variables:
  CI: "false"

client-test: 
  image: node:latest
  stage: client_test
  script:
    - cd client
    - npm install
    - npm build
    - npm test
  artifacts:
    paths:
      - client/node_modules

client-build:
  image: node:latest
  stage: client_build
  script:
    - cd client
    - npm install
    - npm build
  artifacts:
    paths:
      - client/node_modules
    
  
