
stages:         
  - client_install
  - client_test

variables:
  CI: "false"

client-install-job: 
  image: node:latest
  stage: client_install
  script:
    - cd client
    - npm install
  artifacts:
    paths:
      - client/node_modules

client-test-job:
  stage: client_test
  needs: 
    - client-install-job
  script:
    - cd client
    - npm test

    
  
