
stages:         
  - client_test
  - client_build

variables:
  CI: "false"

client-test: 
  image: node:latest
  stage: client_test
  script:
    - cd client
    - npm install
    - npm test

client-build:
  stage: client_build
  script:
    - cd client
    - npm install
    - npm test

    
  
