
stages:        
  - client_build
  - client_test
  - server_build
  - server_test

variables:
  CI: "false"

# CLIENT 

client-build:
  image: node:latest
  stage: client_build
  script:
    - cd client
    - npm install
    - npm run build
  artifacts:
    paths:
      - client/node_modules

client-test: 
  image: node:latest
  stage: client_test
  needs: 
    - client-build
  script:
    - cd client
    - npm install
    - npm run test
  artifacts:
    paths:
      - client/node_modules


# SERVER

server-build:
  image: node:latest
  stage: client_build
  script:
    - cd server
    - npm install
    - npm run build
  artifacts:
    paths:
      - server/node_modules
  
      
server-test: 
  image: node:latest
  stage: client_test
  needs:
    - server-build
  script:
    - cd server
    - npm install
    - npm run test
  artifacts:
    paths:
      - server/node_modules
