
stages:         
  - client_test

variables:
  CI: "false"

client-install-job: 
  image: node:latest
  stage: client_test
  script:
    - cd client
    - npm install
  artifacts:
    paths:
      - client/node_modules

client-test-job:
  stage: client_test
  dependencies: 
    - client-install-job
  script:
    - cd client
    - npm test
  artifacts:
    when: always

    
  
