user_content_persistence:
  url: "neo4j://10.212.172.128:7687"
  usr: "neo4j"
  pwd: "crumbdevsrule"

user_credentials_persistence:
  cluster: "crumbdevs.ta4zcje"
  usr: "crumbdevs"
  pwd: "crumbdevsruler"
  db: "userdata"

authentication_service:
  key: "85dbe15d75ef9308c7ae0f33c7a324cc6f4bf519a2ed2f3027bd33c140a4f9aa"