user_content_persistence:
  url: "neo4j://10.212.173.46:7687"
  usr: "neo4j"
  pwd: "crumbdevsrule"

user_credentials_persistence:
  cluster: "cluster0.x06e66b"
  usr: "crumbdevs_test"
  pwd: "3Rt23jd9oWHqlgpy"
  db: "cluster0"

authentication_service_key:
  key: "85dbe15d75ef9308c7ae0f33c7a324cc6f4bf519a2ed2f3027bd33c140a4f9aa"